### ISSUE TITLE
Invalid glob import syntax: Expect CallExpression, got BinaryExpression

### ISSUE THREAD

**Issue by vallerydelexy** [oedotme/generouted#51]
Invalid glob import syntax: Expect CallExpression, got BinaryExpression
00:00:44 [vite] Internal server error: Invalid glob import syntax: Expect CallExpression, got BinaryExpression
  Plugin: vite:import-glob
  File: D:/test/node_modules/.pnpm/generouted@1.7.13_vite@4.1.2/node_modules/generouted/src/react-router.tsx:10:19

```
  8  |  type Module = { default: Element; Loader: LoaderFunction; Action: ActionFunction; ErrorElement: Element }
  9  |  
  10 |  const PRESERVED = import.meta.glob<Module>('/src/pages/(_app|404).{jsx,tsx}', { eager: true })
     |                    ^
  11 |  const ROUTES = import.meta.glob<Module>(['/src/pages/**/[\\w[]*.{jsx,tsx}', '!**/(_app|404).*'])
  12 |
```

     

>  at err (file:///D:/test/node_modules/.pnpm/vite@4.1.2/node_modules/vite/dist/node/chunks/dep-9912c491.js:37834:23)
>       at file:///D:/test/node_modules/.pnpm/vite@4.1.2/node_modules/vite/dist/node/chunks/dep-9912c491.js:37873:19
>       at Array.map (<anonymous>)
>       at parseImportGlob (file:///D:/test/node_modules/.pnpm/vite@4.1.2/node_modules/vite/dist/node/chunks/dep-9912c491.js:37830:27)
>       at transformGlobImport (file:///D:/test/node_modules/.pnpm/vite@4.1.2/node_modules/vite/dist/node/chunks/dep-9912c491.js:37948:27)
>       at TransformContext.transform (file:///D:/test/node_modules/.pnpm/vite@4.1.2/node_modules/vite/dist/node/chunks/dep-9912c491.js:37755:34)
>       at Object.transform (file:///D:/test/node_modules/.pnpm/vite@4.1.2/node_modules/vite/dist/node/chunks/dep-9912c491.js:41662:44)
>       at async loadAndTransform (file:///D:/test/node_modules/.pnpm/vite@4.1.2/node_modules/vite/dist/node/chunks/dep-9912c491.js:39467:29)

**Comment by vallerydelexy** [comment]
same as https://github.com/oedotme/generouted/issues/37
